language: python
python:
  - '2.6'
  - '2.7'
install:
  - 'pip install -r requirements/basic.txt'
  - 'pip install -r requirements/devel.txt'
  - 'pip install -r requirements/l10n.txt'
script: python run_tests.py
notifications:
  email:
    - neithere+travis@gmail.com
